server:
    port: 8888
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

# spring:
#     datasource:
#         driver-class-name: org.h2.Driver
#         url: jdbc:h2:mem:testdb
#         username: sa
#         password:

spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:XE
        username: JPTEST
        password: 1234

    jpa:
        # generate-ddl: true
        # hibernate:
        #     ddl-auto: update
        #     naming:
        #         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true

    devtools:
        livereload:
            enabled: true
    profiles:
        include:
            - oauth
logging.level:
    org.hibernate.SQL: debug
